project_id = "dfepyvnbeiafyaysbojg"

[functions.record-market-prices]
verify_jwt = false  # Called by cron, uses internal authentication

[functions.import-excel-data]
verify_jwt = true

[functions.fetch-twelve-data]
verify_jwt = false

[functions.get-realtime-price]
verify_jwt = false

[functions.fetch-historical-data]
verify_jwt = false

[functions.send-reset-password-email]
verify_jwt = false

[functions.sync-market-data]
verify_jwt = false  # Epic sync function with internal auth checks
