project_id = "dfepyvnbeiafyaysbojg"

[functions.record-market-prices]
verify_jwt = false

[functions.import-excel-data]
verify_jwt = true

[functions.fetch-twelve-data]
verify_jwt = false

[functions.get-realtime-price]
verify_jwt = false
